name: Test the Backend code

on:
  push:
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    strategy:
      fail-fast: false
      matrix:
        python:
          - "3.8"
          - "3.9"
        plone:
          - "6.0.0a2"

    steps:
      - uses: actions/checkout@v2

      - name: Setup Plone ${{ matrix.plone }} with Python ${{ matrix.python }}
        id: setup
        uses: plone/setup-plone@v1.0.0
        with:
          python-version: ${{ matrix.python }}
          plone-version: ${{ matrix.plone }}

      - name: Install package
        run: |
          make VENV=off install

      - name: Run tests
        run: |
          git config --global url."https://github.com/".insteadOf ssh://git@github.com/
          make VENV=off test-ignore-warnings
